### GET ALL BOOKS
GET http://127.0.0.1:1604/api/books?page=3
### GET A BOOK
GET http://127.0.0.1:1604/api/books/<ID>
### GET ALL AUTHORS
GET http://127.0.0.1:1604/api/authors
### FILTER BOOKS
GET http://127.0.0.1:1604/api/books?category=fiction
### GET BOOKS BY AUTHORS
GET http://127.0.0.1:1604/api/authors/<ID>/books