openapi: 3.0.0
info:
  title: Library Management API
  description: API đơn giản để quản lý đầu sách trong thư viện.
  version: 1.0.0

tags:
  - name: Books
    description: Books Management

paths:
  /books:
    get:
      tags:
        - Books
      summary: Get all books
      description: Return a list of books
      operationId: getBooks
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayResponse'

  /books/{id}:
    parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
    get:
      tags:
        - Books
      summary: Get detail a book
      operationId: getBook
      responses:
        '200':
          description: Success!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ObjectResponse'
        '404':
          description: Not Found!
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
    
components:
  schemas:
    Book:
      type: object
      properties:
        id: { type: integer, example: 1 }
        title: { type: string, example: "De men phieu luu ky" }
        author: { type: string, example: "To Hoai" }
        isbn: { type: string, example: "978-6042168673" }

    ArrayResponse:
      type: object
      properties:
        success: { type: boolean, example: true }
        message: { type: string, example: "Success!" }
        data:
          type: object
          properties:
            items:
              type: array
              items:
                $ref: '#/components/schemas/Book'
      
    ObjectResponse:
      type: object
      properties:
        success: { type: boolean, example: true }
        message: { type: string, example: "Success!" }
        data:
          $ref: '#/components/schemas/Book'
        
    ErrorResponse:
      type: object
      properties:
        success: { type: boolean, example: false }
        message: { type: string, example: "Not Found the book!" }
        data: { nullable: true, example: null }