### GET
GET http://127.0.0.1:1604/api/users
Authorization: password

### POST
POST http://127.0.0.1:1604/api/users
Content-Type: application/json
Authorization: password

{
    "name": "Le Van C",
    "role": "Admin"
}
### PUT
PUT http://127.0.0.1:1604/api/users/<ID>
Content-Type: application/json
Authorization: password

{
    "name": "Nguyen Van A",
    "role": "Super Admin"
}

### PATCH
PATCH http://127.0.0.1:1604/api/users/<ID>
Content-Type: application/json
Authorization: password

{
    "role": "Manager"
}

###  DELETE
DELETE http://127.0.0.1:1604/api/users/<ID>
Authorization: password