### GET
### Muốn thấy tác dụng của cache hãy dùng chomre
### Lần nhập link đầu sẽ cần chờ 10s
### Lần nhập 2 sẽ load đc tức thì
GET http://127.0.0.1:1604/api/users

### POST
POST http://127.0.0.1:1604/api/users
Content-Type: application/json

{
    "name": "Le Van C",
    "role": "Admin"
}
### PUT
PUT http://127.0.0.1:1604/api/users/<ID>
Content-Type: application/json

{
    "name": "Nguyen Van A",
    "role": "Super Admin"
}

### PATCH
PATCH http://127.0.0.1:1604/api/users/<ID>
Content-Type: application/json

{
    "role": "Manager"
}

###  DELETE
DELETE http://127.0.0.1:1604/api/users/<ID>